data_paths:
  raw_data: '../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
  X_test: '../data/processed/X_test.csv'
  y_test: '../data/processed/y_test.csv'

columns:
  id: 'customerID'
  total_charges: 'TotalCharges'
  numeric: ['tenure', 'MonthlyCharges', 'TotalCharges']
  binary: ['gender', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
  multiclass: ['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

train_test_split:
  test_size: 0.2