data_paths:
  raw_data: 'data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
  X_test: 'data/processed/X_test.joblib'
  y_test: 'data/processed/y_test.joblib'

columns:
  id: 'customerID'
  total_charges: 'TotalCharges'
  numeric: ['tenure', 'MonthlyCharges', 'TotalCharges']
  binary: ['gender', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'SeniorCitizen']
  multiclass: ['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

train_test_split:
  test_size: 0.2
  eval_size: 0.2

random_state: 1