model_name: 'logistic_regression'

model_output_paths:
  dir: '../models'
  model: '../models/logistic_regression.joblib'

hyperparams:
  max_iter: 1000
  class_weight: 'balanced'
  cv: 5
  scoring: 'f1'
  n_jobs: 1

param_grid:
  penalty: ['l1', 'l2']
  C:
    start: -4
    stop: 4
    num: 20
  solver: ['liblinear', 'saga']