model_name: 'logistic_regression'

model_output_paths:
  dir: 'models'
  model: 'models/logistic_regression_pipeline.joblib'
  threshold: 'models/logistic_regression_pipeline_threshold.json'

hyperparams:
  cv: 5
  scoring: 'average_precision'
  n_jobs: 1

param_grid:
  penalty: ['l1', 'l2']
  C: [.01, .1, 1, 10]
  solver: ['liblinear']
  max_iter: [5000]
  class_weight: [null] 
  # dropped balanced from here as it proved the None option was picked by GridSearchCV
  # Best params: {'model__C': 1, 'model__class_weight': None, 'model__max_iter': 5000, 'model__penalty': 'l1', 'model__solver': 'liblinear'}