model_name: 'xgboost'

model_output_paths:
  dir: '../models'
  model: '../models/xgboost.joblib'

tune: True

hyperparams:
  cv_size: 0.2
  n_estimators: 1000
  early_stopping_rounds: 10
  objective: 'binary:logistic'
  eval_metric: 'auc'
  tune:
    max_depth:
      min: 3
      max: 11
    learning_rate:
      min: 0.01
      max: 0.2
  n_iter: 50
  cv: 3
  scoring: 'roc_auc'
  n_jobs: 1
  verbose: 1